### ISSUE TITLE
ImportError: warmup_linear in Inference.py 

### ISSUE THREAD

**Issue by syenpark** [arijitx/QnA-Bot#1]
I face ImportError: cannot import name 'warmup_linear' with BERT. I googled that error in the original BERT repository and followed its solution but doesn't work. How would you run it?

**Comment by arijitx** [comment]
I didn't face any such error, can you please share the exact error? Have you installed pytorch-pretrain-bert from git or the default pip one ?

**Comment by syenpark** [comment]
@arijitx First of all, thanks for your reply. I tried installed that pre-trained bert from source and via pip both. Also I tried running your QnA-Bot on Goolge Colab and Google Could PyTorch VM but still face that error. Would you check this notebook?: https://drive.google.com/file/d/119vMtjbssLu8k2WFQMkwJXX024D__W8w/view?usp=sharing

This one is the full directory: https://drive.google.com/drive/folders/1A8R5WJ5lyDUqJvGEiQbWlzRiyi-yIswP?usp=sharing

+++
I suppose your pytorch-pretrain-bert is not up-to-date as 'warmup_linear' is not a function in optimization.py anymore. Would you please let me know which bert version did you use?

**Comment by arijitx** [comment]
Mine version is 0.6.1 looks like your is 0.6.2. My bad I should have mentioned the version correctly. Anyways I'm not sure whether just running server.py will work in a colab environment, because it deploys a flask server. Instead you should use the infer.py to for inference

```
from infer import *
iq = InferCoQA('MODEL_DOWNLOADED_FROM_GOOGLE_DRIVE_DIR')
answer = iq.predict(context,question,prev_q,prev_a)
```

**Comment by syenpark** [comment]
@arijitx Thanks! Yours seems to be implemented especially in 23d4554... among commits related to 0.6.1 version. Thanks for sharing this awesome project although, like you said, I need to resolve a flask server issue now!

**Comment by arijitx** [comment]
I added a commit that will fix the issue and also a colab notebook demo https://colab.research.google.com/drive/1Alz7NMENYc1S28EqUDwbe7hf1M8HpYSO

My model is inside my google drive so first you need upload the model.zip to yours.

**Comment by syenpark** [comment]
@arijitx Genuinely thank you so~ much!
